#-----------------------------#
# brew Tap
#-----------------------------#
tap "turbot/tap"


#-----------------------------#
# brew install applications
#-----------------------------#

## CLI tools
brew "zsh"                      # Shell
brew "git"                      # Source Control
brew "tree"                     # CLI tool
brew "jq"                       # CLI tool
brew "httpie"                   # HTTP
brew "fzf"                      # CLI tool
brew "gh"                       # CLI tool
brew "awscli"                   # AWS Cloud CLI
brew "azure-cli"                # Azure Cloud CLI
brew "node"                     # Language runtime
brew "fzf"                      # Fuzzy Finder
brew "z"                        # CLI tool
brew "zsh-completions"          # zsh
brew "zsh-syntax-highlighting"  # zsh
brew "wget"                     # HTTP
brew "golang"                   # Go Lang
brew "protobuf"                 # Protobuf
brew "helm"                     # K8s Helm
brew "postgresql@14"            # Postgres DB
brew "pyenv"                    # python environment
brew "pyenv-virtualenv"         # python virtualenv

brew "turbot/tap/steampipe"     # Cloud Query Tool from Custom Tap


#-----------------------------#
# cask install applications
#-----------------------------#

## Mac Development Tools
cask "google-chrome"            # Browser
cask "google-drive"             # Google Drive
cask "iterm2"                   # Terminal
cask "warp"                     # Terminal
cask "appcleaner"               # Installer
cask "1password"                # Secret Manager
cask "visual-studio-code"       # Editor
cask "zoom"                     # Video Conference
cask "webex"                    # Video Conference
cask "obsidian"                 # Notes
cask "microsoft-outlook"        # Email Client
cask "google-cloud-sdk"         # Google Cloud
cask "xmind"                    # Mind Map tool
cask "docker"                   # Docker Desktop with K8s
cask "dbeaver-community"        # GUI SQL Editor
cask "postman"                  # Postman ResT API
cask "postman-cli"              # Postman CLI